
export const extraTemplates = [
  // --- BEEF: Brisket (Rubs, Marinades) ---
  {
    id: crypto.randomUUID(),
    title: "Sweet & Smoky Brisket Rub",
    proteinId: "p_brisket",
    cookingMethodId: "m_pellet_grill",
    flavorProfileId: "f_sweet_smoky",
    recipeType: "dry_rub" as const,
    ingredients: ["1/2 cup brown sugar", "1/4 cup smoked paprika", "2 tbsp chili powder", "2 tbsp garlic powder", "2 tbsp onion powder", "1 tbsp salt", "1 tbsp black pepper", "1 tsp cayenne pepper"],
    instructions: ["Mix all ingredients in a bowl.", "Apply liberally to trimmed brisket, ensuring all surfaces are covered.", "Let rest for 30-60 minutes before putting on the grill.", "Cook at 250°F until internal temp reaches 203°F."],
    prepTime: "15 min",
    cookTime: "10-12 hours",
    restingTime: "2 hours",
    targetTempF: 203,
    woodPairings: ["Hickory", "Cherry"],
    sauceRecommendations: ["Sweet Bourbon BBQ Sauce"],
    sideRecommendations: ["Cornbread", "Mac and Cheese"],
    cookingTips: ["Brown sugar helps with bark formation in pellet grills."]
  },
  {
    id: crypto.randomUUID(),
    title: "Savory Herb Brisket Injection",
    proteinId: "p_brisket",
    cookingMethodId: "m_smoker",
    flavorProfileId: "f_savory_herb",
    recipeType: "marinade" as const,
    ingredients: ["2 cups beef broth", "1/4 cup Worcestershire sauce", "2 tbsp soy sauce", "1 tbsp dried thyme", "1 tbsp dried rosemary", "1 tbsp garlic powder", "1 tsp onion powder"],
    instructions: ["Whisk all ingredients together until well combined.", "Using a meat injector, inject the liquid into the thickest parts of the brisket every 2 inches.", "Wipe away excess liquid and apply your favorite rub.", "Smoke as usual."],
    prepTime: "20 min",
    cookTime: "12 hours",
    restingTime: "3 hours",
    targetTempF: 203,
    woodPairings: ["Oak", "Pecan"],
    sauceRecommendations: ["Au Jus", "Red Wine Reduction"],
    sideRecommendations: ["Roasted Root Vegetables", "Creamed Spinach"],
    cookingTips: ["Injecting adds internal moisture and deep savory flavor."]
  },
  {
    id: crypto.randomUUID(),
    title: "Smoky Coffee Brisket Marinade",
    proteinId: "p_brisket",
    cookingMethodId: "m_smoker",
    flavorProfileId: "f_sweet_smoky",
    recipeType: "marinade" as const,
    ingredients: ["1 cup strong black coffee, cooled", "1/2 cup balsamic vinegar", "1/4 cup olive oil", "1/4 cup brown sugar", "2 tbsp Worcestershire sauce", "3 cloves garlic, minced", "1 tbsp smoked paprika"],
    instructions: ["Combine all ingredients in a large container or heavy-duty bag.", "Add brisket and marinate for at least 8 hours, ideally overnight.", "Remove brisket, pat dry, and smoke until tender.", "Discard marinade."],
    prepTime: "8 hours",
    cookTime: "12 hours",
    restingTime: "2 hours",
    targetTempF: 203,
    woodPairings: ["Hickory", "Mesquite"],
    sauceRecommendations: ["Coffee-infused BBQ Sauce"],
    sideRecommendations: ["Hashbrown Casserole", "Brussels Sprouts"],
    cookingTips: ["The acidity in coffee and vinegar helps tenderize the tough brisket fibers."]
  },

  // --- BEEF: Steak (Rubs, Compound Butters, Sauces) ---
  {
    id: crypto.randomUUID(),
    title: "Texas Classic Steak Rub",
    proteinId: "p_steak",
    cookingMethodId: "m_charcoal_grill",
    flavorProfileId: "f_texas_classic",
    recipeType: "dry_rub" as const,
    ingredients: ["2 tbsp kosher salt", "2 tbsp coarse black pepper (16 mesh)", "1 tsp granulated garlic", "1/2 tsp onion powder"],
    instructions: ["Mix ingredients thoroughly.", "Pat steaks dry with a paper towel.", "Season liberally on all sides, including the edges.", "Grill over direct high heat to desired doneness."],
    prepTime: "5 min",
    cookTime: "10 min",
    restingTime: "5 min",
    targetTempF: 135,
    woodPairings: ["Oak", "Hickory"],
    sauceRecommendations: ["Compound Butter"],
    sideRecommendations: ["Grilled Asparagus", "Loaded Baked Potato"],
    cookingTips: ["The coarse pepper creates a fantastic crust (crust) on the steak."]
  },
  {
    id: crypto.randomUUID(),
    title: "Garlic & Herb Compound Butter",
    proteinId: "p_steak",
    cookingMethodId: "m_charcoal_grill",
    flavorProfileId: "f_savory_herb",
    recipeType: "compound_butter" as const,
    ingredients: ["1/2 cup unsalted butter, softened", "2 cloves garlic, minced", "1 tbsp fresh parsley, chopped", "1 tsp fresh thyme, chopped", "1/2 tsp kosher salt", "1/4 tsp black pepper"],
    instructions: ["In a small bowl, combine all ingredients.", "Mix until well combined.", "Place on plastic wrap and roll into a log.", "Refrigerate for at least 1 hour before slicing.", "Top hot steak with a slice of butter just before serving."],
    prepTime: "10 min",
    cookTime: "0 min",
    restingTime: "1 hour",
    targetTempF: 0,
    woodPairings: ["Oak"],
    sauceRecommendations: ["None"],
    sideRecommendations: ["Mashed Potatoes"],
    cookingTips: ["Make this a day ahead to let the flavors fully meld."]
  },
  {
    id: crypto.randomUUID(),
    title: "Blue Cheese & Peppercorn Compound Butter",
    proteinId: "p_steak",
    cookingMethodId: "m_gas_grill",
    flavorProfileId: "f_texas_classic",
    recipeType: "compound_butter" as const,
    ingredients: ["1/2 cup unsalted butter, softened", "1/4 cup crumbled blue cheese", "1 tsp cracked black pepper", "1/2 tsp salt"],
    instructions: ["Mash butter and blue cheese together with a fork.", "Stir in pepper and salt.", "Form into a log and chill.", "Serve a thick slice over a hot seared steak."],
    prepTime: "10 min",
    cookTime: "0 min",
    restingTime: "1 hour",
    targetTempF: 0,
    woodPairings: ["Hickory"],
    sauceRecommendations: ["None"],
    sideRecommendations: ["Steak Fries"],
    cookingTips: ["The sharp blue cheese cuts through the richness of the beef."]
  },
  {
    id: crypto.randomUUID(),
    title: "Classic Chimichurri Sauce",
    proteinId: "p_steak",
    cookingMethodId: "m_charcoal_grill",
    flavorProfileId: "f_savory_herb",
    recipeType: "sauce" as const,
    ingredients: ["1 cup fresh parsley, packed", "4 cloves garlic", "2 tbsp fresh oregano (or 1 tsp dried)", "1/2 cup olive oil", "2 tbsp red wine vinegar", "1 tsp sea salt", "1/4 tsp red pepper flakes"],
    instructions: ["Finely chop parsley, garlic, and oregano.", "Mix in a bowl with oil, vinegar, salt, and pepper flakes.", "Let sit for at least 20 minutes at room temperature before serving.", "Spoon over grilled steak."],
    prepTime: "15 min",
    cookTime: "0 min",
    restingTime: "20 min",
    targetTempF: 0,
    woodPairings: ["Oak"],
    sauceRecommendations: ["None"],
    sideRecommendations: ["Grilled Vegetables"],
    cookingTips: ["Do not use a food processor; hand-chopping gives the best texture."]
  },

  // --- BEEF: Burgers (Rubs, Sauces) ---
  {
    id: crypto.randomUUID(),
    title: "Savory Herb Burger Seasoning",
    proteinId: "p_burgers",
    cookingMethodId: "m_gas_grill",
    flavorProfileId: "f_savory_herb",
    recipeType: "dry_rub" as const,
    ingredients: ["1 tbsp salt", "1 tsp garlic powder", "1 tsp onion powder", "1 tsp dried oregano", "1/2 tsp dried basil", "1/2 tsp black pepper"],
    instructions: ["Mix seasoning.", "Gently mix into ground beef OR sprinkle liberally on patties just before grilling.", "Grill to 160°F internal."],
    prepTime: "10 min",
    cookTime: "8 min",
    restingTime: "3 min",
    targetTempF: 160,
    woodPairings: [],
    sauceRecommendations: ["Garlic Mayo", "Pesto"],
    sideRecommendations: ["Sweet Potato Fries", "Greek Salad"],
    cookingTips: ["For the best texture, don't overwork the meat when mixing."]
  },

  // --- PORK: Butt & Ribs (Rubs, Marinades, Brines, Sauces) ---
  {
    id: crypto.randomUUID(),
    title: "Classic Sweet & Smoky Pork Rub",
    proteinId: "p_pork_butt",
    cookingMethodId: "m_smoker",
    flavorProfileId: "f_sweet_smoky",
    recipeType: "dry_rub" as const,
    ingredients: ["1/2 cup brown sugar", "1/4 cup paprika", "1 tbsp kosher salt", "1 tbsp black pepper", "1 tbsp garlic powder", "1 tbsp onion powder", "1 tsp mustard powder", "1/2 tsp cayenne"],
    instructions: ["Mix all dry ingredients thoroughly.", "Apply a thin layer of yellow mustard as a binder to the pork butt.", "Coat heavily with the rub on all sides.", "Smoke at 225°F until the bark is set (around 165°F internal).", "Wrap in foil and continue until 203°F."],
    prepTime: "20 min",
    cookTime: "8-10 hours",
    restingTime: "1 hour",
    targetTempF: 203,
    woodPairings: ["Hickory", "Apple", "Peach"],
    sauceRecommendations: ["Sweet Tomato-based BBQ Sauce"],
    sideRecommendations: ["Coleslaw", "Baked Beans"],
    cookingTips: ["The mustard binder helps the rub stick without affecting final flavor."]
  },
  {
    id: crypto.randomUUID(),
    title: "Tangy Mustard Pork Marinade",
    proteinId: "p_pork_butt",
    cookingMethodId: "m_smoker",
    flavorProfileId: "f_tangy",
    recipeType: "marinade" as const,
    ingredients: ["1 cup yellow mustard", "1/2 cup apple cider vinegar", "1/4 cup brown sugar", "2 tbsp Worcestershire sauce", "1 tbsp hot sauce", "1 tsp salt", "1 tsp black pepper"],
    instructions: ["Whisk all ingredients together.", "Coat the pork butt in the marinade and let sit in the fridge for at least 4 hours.", "Smoke as usual, using the leftover marinade as a baste during the first few hours."],
    prepTime: "4 hours",
    cookTime: "10 hours",
    restingTime: "1 hour",
    targetTempF: 203,
    woodPairings: ["Pecan", "Oak"],
    sauceRecommendations: ["South Carolina Gold Sauce"],
    sideRecommendations: ["Potato Salad", "Collard Greens"],
    cookingTips: ["Mustard-based marinades are a South Carolina staple for pork."]
  },
  {
    id: crypto.randomUUID(),
    title: "Spicy Chipotle BBQ Sauce",
    proteinId: "p_pork_butt",
    cookingMethodId: "m_smoker",
    flavorProfileId: "f_spicy",
    recipeType: "sauce" as const,
    ingredients: ["1 cup ketchup", "2 tbsp adobo sauce (from chipotle can)", "1 chipotle pepper, minced", "2 tbsp brown sugar", "1 tbsp cider vinegar"],
    instructions: ["Combine all ingredients in a saucepan.", "Simmer for 10 minutes until thick and glossy.", "Serve on the side with pulled pork."],
    prepTime: "5 min",
    cookTime: "10 min",
    restingTime: "0 min",
    targetTempF: 0,
    woodPairings: ["Hickory"],
    sauceRecommendations: ["None"],
    sideRecommendations: ["Corn"],
    cookingTips: ["Add more adobo sauce if you want more smoke and heat."]
  },
  {
    id: crypto.randomUUID(),
    title: "Tangy Apple Juice Rib Brine",
    proteinId: "p_ribs",
    cookingMethodId: "m_smoker",
    flavorProfileId: "f_tangy",
    recipeType: "brine" as const,
    ingredients: ["4 cups apple juice", "1/2 cup apple cider vinegar", "1/4 cup salt", "1/4 cup brown sugar", "4 whole cloves"],
    instructions: ["Mix all ingredients until salt and sugar dissolve.", "Submerge ribs for 4-6 hours.", "Remove, pat dry, and apply a light rub before smoking."],
    prepTime: "6 hours",
    cookTime: "5 hours",
    restingTime: "15 min",
    targetTempF: 195,
    woodPairings: ["Cherry", "Apple"],
    sauceRecommendations: ["Apple Butter BBQ Sauce"],
    sideRecommendations: ["Onion Rings", "Coleslaw"],
    cookingTips: ["Brining ribs makes them exceptionally juicy and slightly cured in flavor."]
  },

  // --- POULTRY: Chicken & Turkey (Rubs, Brines, Glazes) ---
  {
    id: crypto.randomUUID(),
    title: "Classic Savory Herb Chicken Rub",
    proteinId: "p_chicken",
    cookingMethodId: "m_gas_grill",
    flavorProfileId: "f_savory_herb",
    recipeType: "dry_rub" as const,
    ingredients: ["2 tbsp kosher salt", "1 tbsp dried thyme", "1 tbsp dried sage", "1 tbsp dried rosemary", "1 tbsp garlic powder", "1 tbsp onion powder", "1 tsp white pepper"],
    instructions: ["Mix all spices in a small bowl.", "Spatchcock or piece the chicken for even cooking.", "Apply rub under the skin and on the surface.", "Grill over medium heat until 165°F internal."],
    prepTime: "15 min",
    cookTime: "45 min",
    restingTime: "10 min",
    targetTempF: 165,
    woodPairings: ["Apple", "Cherry"],
    sauceRecommendations: ["White Wine Mushroom Sauce"],
    sideRecommendations: ["Roasted Potatoes", "Green Salad"],
    cookingTips: ["Applying rub under the skin seasons the meat directly and prevents the skin from shielding it."]
  },
  {
    id: crypto.randomUUID(),
    title: "Savory Buttermilk Chicken Brine",
    proteinId: "p_chicken",
    cookingMethodId: "m_oven",
    flavorProfileId: "f_savory_herb",
    recipeType: "brine" as const,
    ingredients: ["2 cups buttermilk", "1/4 cup hot sauce", "2 tbsp salt", "1 tbsp garlic powder", "1 tsp black peppercorns"],
    instructions: ["Combine all ingredients in a large bowl or bag.", "Submerge chicken pieces for 4-8 hours.", "Remove from brine, drain excess, and bake at 400°F until golden and cooked through.", "Great for 'oven-fried' style chicken."],
    prepTime: "4 hours",
    cookTime: "40 min",
    restingTime: "5 min",
    targetTempF: 165,
    woodPairings: [],
    sauceRecommendations: ["Ranch dressing", "Honey Mustard"],
    sideRecommendations: ["Mashed Potatoes", "Corn"],
    cookingTips: ["Buttermilk brine is the secret to incredibly juicy and tender chicken."]
  },
  {
    id: crypto.randomUUID(),
    title: "Honey & Smoked Paprika Glaze",
    proteinId: "p_chicken",
    cookingMethodId: "m_pellet_grill",
    flavorProfileId: "f_sweet_smoky",
    recipeType: "glaze" as const,
    ingredients: ["1/2 cup honey", "2 tbsp apple cider vinegar", "1 tbsp smoked paprika", "1 tsp garlic powder", "1/2 tsp cayenne pepper"],
    instructions: ["Whisk all ingredients in a small saucepan.", "Simmer over low heat for 5 minutes until slightly thickened.", "Brush onto chicken during the last 10-15 minutes of cooking.", "Apply in thin layers for a tacky finish."],
    prepTime: "5 min",
    cookTime: "5 min",
    restingTime: "0 min",
    targetTempF: 0,
    woodPairings: ["Cherry", "Apple"],
    sauceRecommendations: ["None"],
    sideRecommendations: ["Cornbread"],
    cookingTips: ["Applying too early will cause the honey to burn; wait until the end."]
  },
  {
    id: crypto.randomUUID(),
    title: "Tangy Apple Cider Vinegar Turkey Brine",
    proteinId: "p_turkey",
    cookingMethodId: "m_pellet_grill",
    flavorProfileId: "f_tangy",
    recipeType: "brine" as const,
    ingredients: ["2 quarts water", "1/2 cup salt", "1/2 cup sugar", "1/2 cup apple cider vinegar", "1 tbsp black peppercorns", "3 bay leaves"],
    instructions: ["Dissolve salt and sugar in 1 quart of warm water.", "Add vinegar, peppercorns, bay leaves, and remaining cold water.", "Brine turkey for 12-24 hours.", "Rinse and pat extremely dry before smoking to ensure crispy skin."],
    prepTime: "24 hours",
    cookTime: "3.5 hours",
    restingTime: "30 min",
    targetTempF: 165,
    woodPairings: ["Cherry", "Oak"],
    sauceRecommendations: ["Mustard-based BBQ Sauce"],
    sideRecommendations: ["Cornbread dressing", "Green Bean Casserole"],
    cookingTips: ["A long brine is essential for whole turkeys to prevent breast meat from drying out."]
  },

  // --- SEAFOOD: Salmon & Shrimp (Rubs, Marinades, Glazes) ---
  {
    id: crypto.randomUUID(),
    title: "Spicy Honey Ginger Salmon Marinade",
    proteinId: "p_salmon",
    cookingMethodId: "m_charcoal_grill",
    flavorProfileId: "f_spicy",
    recipeType: "marinade" as const,
    ingredients: ["2 tbsp honey", "1 tbsp sriracha", "1 tbsp soy sauce", "1 tbsp lime juice", "1 tsp grated ginger", "1 clove garlic, minced"],
    instructions: ["Whisk all ingredients.", "Marinate salmon for 30-60 minutes.", "Grill over medium charcoal heat, basting once with fresh (un-used) marinade.", "Cook until 145°F."],
    prepTime: "1 hour",
    cookTime: "10 min",
    restingTime: "2 min",
    targetTempF: 145,
    woodPairings: ["Oak"],
    sauceRecommendations: ["Extra Sriracha Honey Glaze"],
    sideRecommendations: ["Baby Bok Choy", "Soba Noodles"],
    cookingTips: ["Honey burns easily, so keep a close eye on the charcoal grill."]
  },
  {
    id: crypto.randomUUID(),
    title: "Garlic Butter & Dill Seafood Glaze",
    proteinId: "p_salmon",
    cookingMethodId: "m_gas_grill",
    flavorProfileId: "f_savory_herb",
    recipeType: "glaze" as const,
    ingredients: ["4 tbsp unsalted butter", "2 cloves garlic, minced", "1 tbsp fresh dill, chopped", "1 tsp lemon juice"],
    instructions: ["Melt butter in a small pan.", "Add garlic and sauté for 1 minute until fragrant.", "Stir in dill and lemon juice.", "Brush liberally over salmon or shrimp during the last 3-4 minutes of grilling."],
    prepTime: "5 min",
    cookTime: "2 min",
    restingTime: "0 min",
    targetTempF: 0,
    woodPairings: ["Alder"],
    sauceRecommendations: ["None"],
    sideRecommendations: ["Rice Pilaf"],
    cookingTips: ["Dill and salmon are the ultimate pairing; use fresh dill if possible."]
  },
  {
    id: crypto.randomUUID(),
    title: "Spicy Sriracha Lime Glaze",
    proteinId: "p_shrimp",
    cookingMethodId: "m_charcoal_grill",
    flavorProfileId: "f_spicy",
    recipeType: "glaze" as const,
    ingredients: ["2 tbsp sriracha", "2 tbsp honey", "1 tbsp lime juice", "1 tsp soy sauce"],
    instructions: ["Whisk ingredients together.", "Baste onto shrimp skewers for the last 2 minutes of grilling.", "Turn skewers to ensure even caramelization."],
    prepTime: "5 min",
    cookTime: "0 min",
    restingTime: "0 min",
    targetTempF: 0,
    woodPairings: ["Fruitwood"],
    sauceRecommendations: ["Extra glaze for dipping"],
    sideRecommendations: ["Mango Slaw"],
    cookingTips: ["The heat from the sriracha is balanced by the honey's sweetness."]
  },

  // --- VEGETABLES: Mixed (Marinades, Glazes) ---
  {
    id: crypto.randomUUID(),
    title: "Sweet & Smoky Balsamic Veggie Marinade",
    proteinId: "p_veg_mixed",
    cookingMethodId: "m_gas_grill",
    flavorProfileId: "f_sweet_smoky",
    recipeType: "marinade" as const,
    ingredients: ["1/4 cup balsamic vinegar", "2 tbsp honey", "1/4 cup olive oil", "1/2 tsp liquid smoke", "2 cloves garlic, minced", "Salt and pepper"],
    instructions: ["Whisk ingredients.", "Marinate sturdy veggies (mushrooms, onions, peppers) for 1 hour.", "Grill over medium heat until tender, basting with remaining marinade."],
    prepTime: "1 hour",
    cookTime: "12 min",
    restingTime: "0 min",
    targetTempF: 160,
    woodPairings: [],
    sauceRecommendations: ["Balsamic Glaze"],
    sideRecommendations: ["Polenta", "Crusty Bread"],
    cookingTips: ["Liquid smoke provides that outdoor flavor even on a gas grill."]
  },
  {
    id: crypto.randomUUID(),
    title: "Maple Balsamic Veggie Glaze",
    proteinId: "p_veg_mixed",
    cookingMethodId: "m_oven",
    flavorProfileId: "f_sweet_smoky",
    recipeType: "glaze" as const,
    ingredients: ["2 tbsp balsamic glaze (reduced)", "1 tbsp maple syrup", "1 tbsp olive oil", "1/2 tsp smoked salt"],
    instructions: ["Whisk ingredients until smooth.", "Toss with roasted vegetables halfway through cooking.", "Apply a final coat just before serving."],
    prepTime: "5 min",
    cookTime: "0 min",
    restingTime: "0 min",
    targetTempF: 0,
    woodPairings: ["None"],
    sauceRecommendations: ["None"],
    sideRecommendations: ["Goat Cheese"],
    cookingTips: ["The maple syrup helps the balsamic stick to the veggies and caramelize."]
  },
  {
    id: crypto.randomUUID(),
    title: "Spicy Honey-Harissa Veggie Glaze",
    proteinId: "p_veg_mixed",
    cookingMethodId: "m_charcoal_grill",
    flavorProfileId: "f_spicy",
    recipeType: "glaze" as const,
    ingredients: ["2 tbsp honey", "1 tbsp harissa paste", "1 tbsp lemon juice", "1 tbsp olive oil"],
    instructions: ["Mix all ingredients into a smooth paste.", "Brush over carrots or cauliflower during the last 5 minutes of grilling.", "Caramelize until slightly charred."],
    prepTime: "5 min",
    cookTime: "0 min",
    restingTime: "0 min",
    targetTempF: 0,
    woodPairings: ["Mesquite"],
    sauceRecommendations: ["Yogurt Dip"],
    sideRecommendations: ["Couscous"],
    cookingTips: ["Harissa adds a complex, floral heat that works wonders on roasted roots."]
  },

  // --- ADDITIONAL PORK (Rubs, Marinades, Sauces) ---
  {
    id: crypto.randomUUID(),
    title: "Apple Cider Pork Injection",
    proteinId: "p_pork_butt",
    cookingMethodId: "m_smoker",
    flavorProfileId: "f_tangy",
    recipeType: "marinade" as const,
    ingredients: ["1 cup apple cider", "1/4 cup apple cider vinegar", "2 tbsp Worcestershire sauce", "2 tbsp melted butter", "1 tsp salt"],
    instructions: ["Combine all ingredients and whisk well.", "Inject into the pork butt every 2 inches.", "Wipe excess and apply rub.", "The injection keeps the meat juicy during 10+ hour smokes."],
    prepTime: "15 min",
    cookTime: "10 hours",
    restingTime: "1 hour",
    targetTempF: 203,
    woodPairings: ["Apple", "Pecan"],
    sauceRecommendations: ["Apple Butter BBQ Sauce"],
    sideRecommendations: ["Potato Salad"],
    cookingTips: ["Injection is superior to marinating for large cuts like pork shoulder."]
  },
  {
    id: crypto.randomUUID(),
    title: "Coffee & Black Pepper Pork Rub",
    proteinId: "p_pork_butt",
    cookingMethodId: "m_smoker",
    flavorProfileId: "f_texas_classic",
    recipeType: "dry_rub" as const,
    ingredients: ["1/4 cup finely ground coffee", "1/4 cup coarse black pepper", "2 tbsp kosher salt", "1 tbsp garlic powder"],
    instructions: ["Mix ingredients.", "Apply liberally to pork butt.", "Smoke at 250°F until internal temp hits 203°F.", "Creates a savory, dark bark without the sweetness."],
    prepTime: "10 min",
    cookTime: "9 hours",
    restingTime: "1 hour",
    targetTempF: 203,
    woodPairings: ["Oak", "Hickory"],
    sauceRecommendations: ["Vinegar Mop"],
    sideRecommendations: ["Coleslaw"],
    cookingTips: ["Coffee helps develop a deep, rich color on the bark."]
  },

  // --- ADDITIONAL CHICKEN (Rubs, Brines, Glazes) ---
  {
    id: crypto.randomUUID(),
    title: "Spicy Ghost Pepper Chicken Glaze",
    proteinId: "p_chicken",
    cookingMethodId: "m_gas_grill",
    flavorProfileId: "f_spicy",
    recipeType: "glaze" as const,
    ingredients: ["1/2 cup apricot preserves", "1 tsp ghost pepper hot sauce (adjust to taste)", "1 tbsp soy sauce", "1 tbsp lime juice"],
    instructions: ["Warm apricot preserves until liquid.", "Stir in hot sauce, soy, and lime.", "Brush onto chicken wings or thighs during the last 5 minutes of grilling."],
    prepTime: "5 min",
    cookTime: "5 min",
    restingTime: "0 min",
    targetTempF: 0,
    woodPairings: ["Hickory"],
    sauceRecommendations: ["Blue Cheese Dressing"],
    sideRecommendations: ["Celery Sticks"],
    cookingTips: ["The fruit preserves provide a perfect sticky base for extreme heat."]
  },
  // --- FINAL ADDITIONS FOR FULL COVERAGE ---
  {
    id: crypto.randomUUID(),
    title: "Horseradish & Chive Compound Butter",
    proteinId: "p_steak",
    cookingMethodId: "m_gas_grill",
    flavorProfileId: "f_savory_herb",
    recipeType: "compound_butter" as const,
    ingredients: ["1/2 cup softened butter", "2 tbsp prepared horseradish", "1 tbsp chopped fresh chives", "1/2 tsp sea salt"],
    instructions: ["Mix ingredients until uniform.", "Roll in parchment paper and chill for 1 hour.", "Serve over hot steak for a sharp, savory finish."],
    prepTime: "10 min",
    cookTime: "0 min",
    restingTime: "1 hour",
    targetTempF: 0,
    woodPairings: ["Oak"],
    sauceRecommendations: ["None"],
    sideRecommendations: ["Steak fries"],
    cookingTips: ["Horseradish adds a distinct heat that pairs beautifully with fatty steaks like Ribeye."]
  },
  {
    id: crypto.randomUUID(),
    title: "Classic Red Wine Pan Sauce",
    proteinId: "p_steak",
    cookingMethodId: "m_charcoal_grill",
    flavorProfileId: "f_texas_classic",
    recipeType: "sauce" as const,
    ingredients: ["1/2 cup dry red wine (Cabernet)", "1/2 cup beef stock", "1 tbsp shallot, minced", "1 tbsp butter", "1 tsp cracked black pepper"],
    instructions: ["After grilling steaks, use a pan to sauté shallots in butter.", "Deglaze with red wine, scraping up any bits.", "Add stock and pepper; reduce by half until syrupy.", "Whisk in a knob of cold butter at the end for shine."],
    prepTime: "5 min",
    cookTime: "10 min",
    restingTime: "0 min",
    targetTempF: 0,
    woodPairings: ["Oak"],
    sauceRecommendations: ["None"],
    sideRecommendations: ["Roasted vegetables"],
    cookingTips: ["Don't use 'cooking wine'; use a wine you would actually drink."]
  },
  {
    id: crypto.randomUUID(),
    title: "Lemon Garlic & Herb Seafood Marinade",
    proteinId: "p_salmon",
    cookingMethodId: "m_gas_grill",
    flavorProfileId: "f_savory_herb",
    recipeType: "marinade" as const,
    ingredients: ["1/4 cup olive oil", "2 tbsp lemon juice", "3 cloves garlic, minced", "1 tsp dried dill", "1/2 tsp salt"],
    instructions: ["Whisk ingredients.", "Marinate salmon or white fish for 30 minutes.", "Grill over medium-high heat until opaque."],
    prepTime: "30 min",
    cookTime: "10 min",
    restingTime: "0 min",
    targetTempF: 145,
    woodPairings: ["Alder"],
    sauceRecommendations: ["Lemon butter glaze"],
    sideRecommendations: ["Rice"],
    cookingTips: ["Seafood marinades should be short to avoid 'cooking' the fish in acid."]
  },
  {
    id: crypto.randomUUID(),
    title: "Apple Cider & Mustard Poultry Brine",
    proteinId: "p_chicken",
    cookingMethodId: "m_smoker",
    flavorProfileId: "f_tangy",
    recipeType: "brine" as const,
    ingredients: ["4 cups apple cider", "1/4 cup kosher salt", "2 tbsp yellow mustard", "1 tbsp black peppercorns"],
    instructions: ["Mix until salt is dissolved.", "Submerge chicken for 4 hours.", "The cider adds sweetness while the mustard provides a tangy foundation."],
    prepTime: "4 hours",
    cookTime: "2 hours",
    restingTime: "10 min",
    targetTempF: 165,
    woodPairings: ["Apple"],
    sauceRecommendations: ["Carolina Gold Sauce"],
    sideRecommendations: ["Potato salad"],
    cookingTips: ["Apple cider is a great natural sweetener for poultry brines."]
  },
  {
    id: crypto.randomUUID(),
    title: "Sage & Onion Turkey Rub",
    proteinId: "p_turkey",
    cookingMethodId: "m_oven",
    flavorProfileId: "f_savory_herb",
    recipeType: "dry_rub" as const,
    ingredients: ["2 tbsp dried sage", "1 tbsp onion powder", "1 tbsp garlic powder", "1 tbsp salt", "1 tsp black pepper"],
    instructions: ["Combine all spices.", "Rub liberally over turkey, including under the skin.", "Roast until 165°F internal."],
    prepTime: "10 min",
    cookTime: "3 hours",
    restingTime: "20 min",
    targetTempF: 165,
    woodPairings: ["Pecan"],
    sauceRecommendations: ["Turkey Gravy"],
    sideRecommendations: ["Stuffing"],
    cookingTips: ["Sage is the quintessential turkey herb."]
  },
  {
    id: crypto.randomUUID(),
    title: "Zesty Italian Veggie Marinade",
    proteinId: "p_veg_mixed",
    cookingMethodId: "m_gas_grill",
    flavorProfileId: "f_savory_herb",
    recipeType: "marinade" as const,
    ingredients: ["1/2 cup olive oil", "1/4 cup red wine vinegar", "1 tsp dried oregano", "1 tsp garlic powder", "1/2 tsp red pepper flakes"],
    instructions: ["Whisk ingredients.", "Toss with vegetables and marinate for 1 hour.", "Grill until tender and charred."],
    prepTime: "1 hour",
    cookTime: "10 min",
    restingTime: "0 min",
    targetTempF: 160,
    woodPairings: [],
    sauceRecommendations: ["Extra marinade for drizzling"],
    sideRecommendations: ["Grilled bread"],
    cookingTips: ["Works great on zucchini, bell peppers, and onions."]
  },
  {
    id: crypto.randomUUID(),
    title: "Tangy BBQ Special Sauce",
    proteinId: "p_burgers",
    cookingMethodId: "m_gas_grill",
    flavorProfileId: "f_tangy",
    recipeType: "sauce" as const,
    ingredients: ["1/2 cup mayonnaise", "2 tbsp yellow mustard", "1 tbsp sweet relish", "1 tsp smoked paprika", "1/2 tsp garlic powder"],
    instructions: ["Whisk all ingredients until smooth.", "Let sit for 30 minutes in the fridge for flavors to meld.", "Spread on toasted burger buns."],
    prepTime: "30 min",
    cookTime: "0 min",
    restingTime: "0 min",
    targetTempF: 0,
    woodPairings: [],
    sauceRecommendations: ["None"],
    sideRecommendations: ["French fries"],
    cookingTips: ["The mustard and relish provide a classic 'burger stand' tang."]
  },
  {
    id: crypto.randomUUID(),
    title: "Zesty Tequila Lime Shrimp Marinade",
    proteinId: "p_shrimp",
    cookingMethodId: "m_charcoal_grill",
    flavorProfileId: "f_spicy",
    recipeType: "marinade" as const,
    ingredients: ["2 tbsp tequila", "2 tbsp lime juice", "1 tbsp olive oil", "1 jalapeño, minced", "1/4 cup fresh cilantro"],
    instructions: ["Mix all ingredients.", "Marinate shrimp for 20 minutes (not longer).", "Grill quickly over high heat."],
    prepTime: "20 min",
    cookTime: "4 min",
    restingTime: "0 min",
    targetTempF: 145,
    woodPairings: ["Mesquite"],
    sauceRecommendations: ["Extra lime wedges"],
    sideRecommendations: ["Street corn"],
    cookingTips: ["Tequila and lime provide a bright, acidic bite that's perfect for shrimp tacos."]
  },
  {
    id: crypto.randomUUID(),
    title: "Cranberry & Sage Turkey Glaze",
    proteinId: "p_turkey",
    cookingMethodId: "m_smoker",
    flavorProfileId: "f_savory_herb",
    recipeType: "glaze" as const,
    ingredients: ["1/2 cup cranberry sauce", "2 tbsp honey", "1 tsp dried sage", "1 tsp orange zest"],
    instructions: ["Heat ingredients in a small saucepan until melted.", "Brush over turkey during the last 30 minutes of smoking."],
    prepTime: "5 min",
    cookTime: "5 min",
    restingTime: "0 min",
    targetTempF: 0,
    woodPairings: ["Cherry"],
    sauceRecommendations: ["None"],
    sideRecommendations: ["Mashed potatoes"],
    cookingTips: ["The cranberry adds a beautiful color and traditional flavor to the bird."]
  }
];
