export const extraTemplates = [
  // --- BEEF ---
  // Brisket (Current: 1 Rub [Texas Classic])
  {
    id: crypto.randomUUID(),
    title: "Sweet & Smoky Brisket Rub",
    proteinId: "p_brisket",
    cookingMethodId: "m_pellet_grill",
    flavorProfileId: "f_sweet_smoky",
    recipeType: "dry_rub" as const,
    ingredients: ["1/2 cup brown sugar", "1/4 cup smoked paprika", "2 tbsp chili powder", "2 tbsp garlic powder", "2 tbsp onion powder", "1 tbsp salt", "1 tbsp black pepper", "1 tsp cayenne pepper"],
    instructions: ["Mix all ingredients in a bowl.", "Apply liberally to trimmed brisket, ensuring all surfaces are covered.", "Let rest for 30-60 minutes before putting on the grill.", "Cook at 250°F until internal temp reaches 203°F."],
    prepTime: "15 min",
    cookTime: "10-12 hours",
    restingTime: "2 hours",
    targetTempF: 203,
    woodPairings: ["Hickory", "Cherry"],
    sauceRecommendations: ["Sweet Bourbon BBQ Sauce"],
    sideRecommendations: ["Cornbread", "Mac and Cheese"],
    cookingTips: ["Brown sugar helps with bark formation in pellet grills."]
  },
  {
    id: crypto.randomUUID(),
    title: "Savory Herb Brisket Injection",
    proteinId: "p_brisket",
    cookingMethodId: "m_smoker",
    flavorProfileId: "f_savory_herb",
    recipeType: "marinade" as const,
    ingredients: ["2 cups beef broth", "1/4 cup Worcestershire sauce", "2 tbsp soy sauce", "1 tbsp dried thyme", "1 tbsp dried rosemary", "1 tbsp garlic powder", "1 tsp onion powder"],
    instructions: ["Whisk all ingredients together until well combined.", "Using a meat injector, inject the liquid into the thickest parts of the brisket every 2 inches.", "Wipe away excess liquid and apply your favorite rub.", "Smoke as usual."],
    prepTime: "20 min",
    cookTime: "12 hours",
    restingTime: "3 hours",
    targetTempF: 203,
    woodPairings: ["Oak", "Pecan"],
    sauceRecommendations: ["Au Jus", "Red Wine Reduction"],
    sideRecommendations: ["Roasted Root Vegetables", "Creamed Spinach"],
    cookingTips: ["Injecting adds internal moisture and deep savory flavor."]
  },
  {
    id: crypto.randomUUID(),
    title: "Smoky Coffee Brisket Marinade",
    proteinId: "p_brisket",
    cookingMethodId: "m_smoker",
    flavorProfileId: "f_sweet_smoky",
    recipeType: "marinade" as const,
    ingredients: ["1 cup strong black coffee, cooled", "1/2 cup balsamic vinegar", "1/4 cup olive oil", "1/4 cup brown sugar", "2 tbsp Worcestershire sauce", "3 cloves garlic, minced", "1 tbsp smoked paprika"],
    instructions: ["Combine all ingredients in a large container or heavy-duty bag.", "Add brisket and marinate for at least 8 hours, ideally overnight.", "Remove brisket, pat dry, and smoke until tender.", "Discard marinade."],
    prepTime: "8 hours",
    cookTime: "12 hours",
    restingTime: "2 hours",
    targetTempF: 203,
    woodPairings: ["Hickory", "Mesquite"],
    sauceRecommendations: ["Coffee-infused BBQ Sauce"],
    sideRecommendations: ["Hashbrown Casserole", "Brussels Sprouts"],
    cookingTips: ["The acidity in coffee and vinegar helps tenderize the tough brisket fibers."]
  },
  {
    id: crypto.randomUUID(),
    title: "Texas Classic Brisket Brine",
    proteinId: "p_brisket",
    cookingMethodId: "m_smoker",
    flavorProfileId: "f_texas_classic",
    recipeType: "brine" as const,
    ingredients: ["1 gallon water", "1 cup kosher salt", "1/2 cup coarse black pepper", "1/4 cup sugar", "4 cloves garlic, crushed"],
    instructions: ["Heat 2 cups of water with salt and sugar until dissolved.", "Add remaining water and let cool completely.", "Submerge brisket in brine for 12-24 hours in the refrigerator.", "Remove, pat dry, and apply salt/pepper rub before smoking."],
    prepTime: "24 hours",
    cookTime: "12 hours",
    restingTime: "3 hours",
    targetTempF: 203,
    woodPairings: ["Post Oak"],
    sauceRecommendations: ["None"],
    sideRecommendations: ["Pinto Beans", "Potato Salad"],
    cookingTips: ["Brining ensures every bite of the brisket is perfectly seasoned."]
  },

  // Steak (Current: 1 Marinade [Savory Herb])
  {
    id: crypto.randomUUID(),
    title: "Texas Classic Steak Rub",
    proteinId: "p_steak",
    cookingMethodId: "m_charcoal_grill",
    flavorProfileId: "f_texas_classic",
    recipeType: "dry_rub" as const,
    ingredients: ["2 tbsp kosher salt", "2 tbsp coarse black pepper (16 mesh)", "1 tsp granulated garlic", "1/2 tsp onion powder"],
    instructions: ["Mix ingredients thoroughly.", "Pat steaks dry with a paper towel.", "Season liberally on all sides, including the edges.", "Grill over direct high heat to desired doneness."],
    prepTime: "5 min",
    cookTime: "10 min",
    restingTime: "5 min",
    targetTempF: 135,
    woodPairings: ["Oak", "Hickory"],
    sauceRecommendations: ["Compound Butter"],
    sideRecommendations: ["Grilled Asparagus", "Loaded Baked Potato"],
    cookingTips: ["The coarse pepper creates a fantastic crust (crust) on the steak."]
  },
  {
    id: crypto.randomUUID(),
    title: "Savory Garlic & Herb Steak Rub",
    proteinId: "p_steak",
    cookingMethodId: "m_gas_grill",
    flavorProfileId: "f_savory_herb",
    recipeType: "dry_rub" as const,
    ingredients: ["2 tbsp kosher salt", "1 tbsp dried rosemary", "1 tbsp dried thyme", "1 tbsp garlic powder", "1 tsp onion powder", "1 tsp black pepper"],
    instructions: ["Crush rosemary and thyme slightly with a mortar and pestle.", "Combine with other spices.", "Rub onto steaks at least 30 minutes before grilling.", "Grill over medium-high heat."],
    prepTime: "35 min",
    cookTime: "12 min",
    restingTime: "5 min",
    targetTempF: 140,
    woodPairings: ["Oak"],
    sauceRecommendations: ["Chimichurri"],
    sideRecommendations: ["Garlic Mashed Potatoes", "Side Salad"],
    cookingTips: ["Letting the rub sit helps the salt penetrate the meat."]
  },
  {
    id: crypto.randomUUID(),
    title: "Texas Classic Steak Marinade",
    proteinId: "p_steak",
    cookingMethodId: "m_charcoal_grill",
    flavorProfileId: "f_texas_classic",
    recipeType: "marinade" as const,
    ingredients: ["1/2 cup olive oil", "1/4 cup soy sauce", "2 tbsp Worcestershire sauce", "1 tbsp coarse black pepper", "1 tsp salt", "2 cloves garlic, smashed"],
    instructions: ["Whisk oil, soy sauce, Worcestershire, pepper, and salt.", "Place steaks in a bag with the marinade and garlic.", "Marinate for 2-4 hours.", "Remove from marinade and grill over high charcoal heat."],
    prepTime: "2 hours",
    cookTime: "10 min",
    restingTime: "8 min",
    targetTempF: 135,
    woodPairings: ["Mesquite"],
    sauceRecommendations: ["Steak Sauce"],
    sideRecommendations: ["Onion Rings", "Sautéed Mushrooms"],
    cookingTips: ["Soy sauce provides deep umami that complements the beef."]
  },
  {
    id: crypto.randomUUID(),
    title: "Savory Herb Steak Brine",
    proteinId: "p_steak",
    cookingMethodId: "m_charcoal_grill",
    flavorProfileId: "f_savory_herb",
    recipeType: "brine" as const,
    ingredients: ["4 cups water", "1/4 cup kosher salt", "2 tbsp sugar", "2 sprigs fresh rosemary", "4 sprigs fresh thyme", "2 cloves garlic", "1 tsp black peppercorns"],
    instructions: ["Bring 1 cup water, salt, and sugar to a boil to dissolve.", "Add remaining water and herbs; let cool.", "Brine steaks for 1 hour (don't overdo it for steak).", "Rinse, pat dry, and grill."],
    prepTime: "1.5 hours",
    cookTime: "10 min",
    restingTime: "5 min",
    targetTempF: 130,
    woodPairings: ["Oak"],
    sauceRecommendations: ["Béarnaise Sauce"],
    sideRecommendations: ["Creamed Corn", "Green Beans"],
    cookingTips: ["Wet brining steak helps it stay incredibly juicy, especially leaner cuts like sirloin."]
  },
  {
    id: crypto.randomUUID(),
    title: "Sweet & Smoky Coffee Steak Rub",
    proteinId: "p_steak",
    cookingMethodId: "m_charcoal_grill",
    flavorProfileId: "f_sweet_smoky",
    recipeType: "dry_rub" as const,
    ingredients: ["2 tbsp finely ground coffee", "2 tbsp brown sugar", "1 tbsp smoked paprika", "1 tbsp kosher salt", "1 tsp black pepper", "1/2 tsp onion powder"],
    instructions: ["Mix all ingredients in a small bowl.", "Apply heavily to all sides of the steak.", "Let sit at room temperature for 30 minutes.", "Grill over high heat to desired doneness."],
    prepTime: "35 min",
    cookTime: "10 min",
    restingTime: "10 min",
    targetTempF: 135,
    woodPairings: ["Oak", "Hickory"],
    sauceRecommendations: ["Red Wine Jus"],
    sideRecommendations: ["Fingerling Potatoes", "Balsamic Glazed Carrots"],
    cookingTips: ["The coffee adds a deep, earthy crust that pairs perfectly with the sweetness of the sugar."]
  },

  // Burgers (Current: 1 Rub [Sweet & Smoky])
  {
    id: crypto.randomUUID(),
    title: "Savory Herb Burger Seasoning",
    proteinId: "p_burgers",
    cookingMethodId: "m_gas_grill",
    flavorProfileId: "f_savory_herb",
    recipeType: "dry_rub" as const,
    ingredients: ["1 tbsp salt", "1 tsp garlic powder", "1 tsp onion powder", "1 tsp dried oregano", "1/2 tsp dried basil", "1/2 tsp black pepper"],
    instructions: ["Mix seasoning.", "Gently mix into ground beef OR sprinkle liberally on patties just before grilling.", "Grill to 160°F internal."],
    prepTime: "10 min",
    cookTime: "8 min",
    restingTime: "3 min",
    targetTempF: 160,
    woodPairings: [],
    sauceRecommendations: ["Garlic Mayo", "Pesto"],
    sideRecommendations: ["Sweet Potato Fries", "Greek Salad"],
    cookingTips: ["For the best texture, don't overwork the meat when mixing."]
  },
  {
    id: crypto.randomUUID(),
    title: "Savory Herb Burger Marinade",
    proteinId: "p_burgers",
    cookingMethodId: "m_gas_grill",
    flavorProfileId: "f_savory_herb",
    recipeType: "marinade" as const,
    ingredients: ["1/4 cup olive oil", "2 tbsp red wine vinegar", "1 tbsp Worcestershire sauce", "1 tsp dried rosemary", "1 tsp dried thyme", "1/2 tsp salt"],
    instructions: ["Whisk all ingredients.", "Place burger patties in a single layer and pour marinade over.", "Marinate for 30-60 minutes.", "Grill over medium-high heat."],
    prepTime: "1 hour",
    cookTime: "10 min",
    restingTime: "2 min",
    targetTempF: 160,
    woodPairings: [],
    sauceRecommendations: ["Aioli"],
    sideRecommendations: ["Pasta Salad", "Zucchini Fries"],
    cookingTips: ["Marinating patties adds moisture that prevents drying out on the gas grill."]
  },
  {
    id: crypto.randomUUID(),
    title: "Texas Classic Burger Injection/Marinade",
    proteinId: "p_burgers",
    cookingMethodId: "m_charcoal_grill",
    flavorProfileId: "f_texas_classic",
    recipeType: "marinade" as const,
    ingredients: ["1/4 cup beef broth", "1 tbsp Worcestershire sauce", "1 tsp coarse black pepper", "1/2 tsp salt"],
    instructions: ["Mix ingredients.", "Briefly marinate patties (15-20 mins) or gently fold the liquid into the ground beef.", "Grill over hot coals."],
    prepTime: "20 min",
    cookTime: "8 min",
    restingTime: "2 min",
    targetTempF: 160,
    woodPairings: ["Hickory"],
    sauceRecommendations: ["Yellow Mustard", "Texas BBQ Sauce"],
    sideRecommendations: ["Potato Wedges", "Pickle Spears"],
    cookingTips: ["Beef broth boosts the 'meaty' flavor profile."]
  },
  {
    id: crypto.randomUUID(),
    title: "Sweet & Smoky Burger Brine",
    proteinId: "p_burgers",
    cookingMethodId: "m_oven",
    flavorProfileId: "f_sweet_smoky",
    recipeType: "brine" as const,
    ingredients: ["2 cups water", "2 tbsp salt", "2 tbsp brown sugar", "1 tsp liquid smoke (optional if baking)", "1/2 tsp smoked paprika"],
    instructions: ["Dissolve salt and sugar in water; add paprika and liquid smoke.", "Submerge patties for 30 minutes.", "Pat dry and bake at 400°F until done.", "The brine keeps oven-baked burgers juicy."],
    prepTime: "40 min",
    cookTime: "15 min",
    restingTime: "3 min",
    targetTempF: 160,
    woodPairings: [],
    sauceRecommendations: ["Chipotle Ketchup"],
    sideRecommendations: ["Tater Tots", "Baked Beans"],
    cookingTips: ["Liquid smoke helps mimic that outdoor flavor when cooking in the oven."]
  },
  // --- PORK ---
  // Pork Butt (Current: 1 Brine [Tangy])
  {
    id: crypto.randomUUID(),
    title: "Classic Sweet & Smoky Pork Rub",
    proteinId: "p_pork_butt",
    cookingMethodId: "m_smoker",
    flavorProfileId: "f_sweet_smoky",
    recipeType: "dry_rub" as const,
    ingredients: ["1/2 cup brown sugar", "1/4 cup paprika", "1 tbsp kosher salt", "1 tbsp black pepper", "1 tbsp garlic powder", "1 tbsp onion powder", "1 tsp mustard powder", "1/2 tsp cayenne"],
    instructions: ["Mix all dry ingredients thoroughly.", "Apply a thin layer of yellow mustard as a binder to the pork butt.", "Coat heavily with the rub on all sides.", "Smoke at 225°F until the bark is set (around 165°F internal).", "Wrap in foil and continue until 203°F."],
    prepTime: "20 min",
    cookTime: "8-10 hours",
    restingTime: "1 hour",
    targetTempF: 203,
    woodPairings: ["Hickory", "Apple", "Peach"],
    sauceRecommendations: ["Sweet Tomato-based BBQ Sauce"],
    sideRecommendations: ["Coleslaw", "Baked Beans"],
    cookingTips: ["The mustard binder helps the rub stick without affecting final flavor."]
  },
  {
    id: crypto.randomUUID(),
    title: "Chipotle Spicy Pork Rub",
    proteinId: "p_pork_butt",
    cookingMethodId: "m_pellet_grill",
    flavorProfileId: "f_spicy",
    recipeType: "dry_rub" as const,
    ingredients: ["2 tbsp chipotle powder", "2 tbsp smoked paprika", "1 tbsp chili powder", "1 tbsp salt", "1 tbsp black pepper", "1 tsp cumin", "1 tsp cayenne pepper"],
    instructions: ["Combine all spices.", "Rub onto pork butt liberally.", "Smoke at 250°F until internal temp reaches 203°F.", "Let rest before pulling."],
    prepTime: "10 min",
    cookTime: "9 hours",
    restingTime: "45 min",
    targetTempF: 203,
    woodPairings: ["Mesquite", "Hickory"],
    sauceRecommendations: ["Spicy Vinegar Sauce"],
    sideRecommendations: ["Jalapeño Cornbread", "Pickled Onions"],
    cookingTips: ["Chipotle powder adds a nice earthy heat and extra smokiness."]
  },
  {
    id: crypto.randomUUID(),
    title: "Tangy Mustard Pork Marinade",
    proteinId: "p_pork_butt",
    cookingMethodId: "m_smoker",
    flavorProfileId: "f_tangy",
    recipeType: "marinade" as const,
    ingredients: ["1 cup yellow mustard", "1/2 cup apple cider vinegar", "1/4 cup brown sugar", "2 tbsp Worcestershire sauce", "1 tbsp hot sauce", "1 tsp salt", "1 tsp black pepper"],
    instructions: ["Whisk all ingredients together.", "Coat the pork butt in the marinade and let sit in the fridge for at least 4 hours.", "Smoke as usual, using the leftover marinade as a baste during the first few hours."],
    prepTime: "4 hours",
    cookTime: "10 hours",
    restingTime: "1 hour",
    targetTempF: 203,
    woodPairings: ["Pecan", "Oak"],
    sauceRecommendations: ["South Carolina Gold Sauce"],
    sideRecommendations: ["Potato Salad", "Collard Greens"],
    cookingTips: ["Mustard-based marinades are a South Carolina staple for pork."]
  },
  {
    id: crypto.randomUUID(),
    title: "Spicy Pineapple Pork Marinade",
    proteinId: "p_pork_butt",
    cookingMethodId: "m_pellet_grill",
    flavorProfileId: "f_spicy",
    recipeType: "marinade" as const,
    ingredients: ["1 cup pineapple juice", "1/4 cup soy sauce", "2 tbsp lime juice", "1 habanero pepper, seeded and minced", "2 cloves garlic, minced", "1 tsp ginger, grated"],
    instructions: ["Mix ingredients in a large bag.", "Marinate pork butt for 6-12 hours.", "Remove and pat dry before smoking.", "Cook at 225°F until probe tender."],
    prepTime: "6 hours",
    cookTime: "10 hours",
    restingTime: "1 hour",
    targetTempF: 203,
    woodPairings: ["Fruitwood (Apple or Cherry)"],
    sauceRecommendations: ["Habanero Pineapple Glaze"],
    sideRecommendations: ["Coconut Rice", "Grilled Pineapple"],
    cookingTips: ["Pineapple juice contains enzymes that help tenderize the meat, but don't marinate too long or it gets mushy."]
  },

  // Ribs (Current: 1 Rub [Sweet & Smoky])
  {
    id: crypto.randomUUID(),
    title: "Spicy Red Pepper Rib Rub",
    proteinId: "p_ribs",
    cookingMethodId: "m_smoker",
    flavorProfileId: "f_spicy",
    recipeType: "dry_rub" as const,
    ingredients: ["2 tbsp black pepper", "1 tbsp salt", "1 tbsp chili flakes", "1 tbsp cayenne pepper", "1 tbsp garlic powder", "1 tsp cumin"],
    instructions: ["Remove membrane from ribs.", "Apply rub to both sides.", "Smoke at 225°F for 3 hours.", "Wrap with a little apple juice for 2 hours.", "Unwrap and glaze for 1 hour."],
    prepTime: "15 min",
    cookTime: "6 hours",
    restingTime: "15 min",
    targetTempF: 195,
    woodPairings: ["Hickory"],
    sauceRecommendations: ["Spicy BBQ Sauce"],
    sideRecommendations: ["Corn on the cob", "French Fries"],
    cookingTips: ["The 3-2-1 method is perfect for fall-off-the-bone ribs."]
  },
  {
    id: crypto.randomUUID(),
    title: "Tangy Apple Vinegar Rib Marinade",
    proteinId: "p_ribs",
    cookingMethodId: "m_charcoal_grill",
    flavorProfileId: "f_tangy",
    recipeType: "marinade" as const,
    ingredients: ["1 cup apple cider vinegar", "1/4 cup water", "2 tbsp brown sugar", "1 tbsp hot sauce", "1 tsp salt", "1 tsp red pepper flakes"],
    instructions: ["Whisk ingredients.", "Place ribs in a shallow dish and cover with marinade.", "Marinate for 2 hours in the fridge.", "Grill over indirect charcoal heat until tender."],
    prepTime: "2 hours",
    cookTime: "4 hours",
    restingTime: "10 min",
    targetTempF: 195,
    woodPairings: ["Apple"],
    sauceRecommendations: ["Vinegar Mop"],
    sideRecommendations: ["Cucumber Salad", "Hush Puppies"],
    cookingTips: ["Vinegar helps cut through the richness of the pork fat."]
  },
  {
    id: crypto.randomUUID(),
    title: "Sweet Bourbon Peach Rib Marinade",
    proteinId: "p_ribs",
    cookingMethodId: "m_gas_grill",
    flavorProfileId: "f_sweet_smoky",
    recipeType: "marinade" as const,
    ingredients: ["1 cup peach nectar", "1/4 cup bourbon", "1/4 cup brown sugar", "2 tbsp soy sauce", "1 tsp liquid smoke"],
    instructions: ["Combine all ingredients.", "Marinate ribs for 4 hours.", "Grill indirect on gas grill, basting with remaining marinade (boiled first).", "Cook until tender."],
    prepTime: "4 hours",
    cookTime: "4 hours",
    restingTime: "15 min",
    targetTempF: 195,
    woodPairings: [],
    sauceRecommendations: ["Peach BBQ Sauce"],
    sideRecommendations: ["Grilled Peaches", "Sweet Potato Wedges"],
    cookingTips: ["Peach and bourbon are a classic Southern flavor pairing."]
  },
  {
    id: crypto.randomUUID(),
    title: "Tangy Apple Juice Rib Brine",
    proteinId: "p_ribs",
    cookingMethodId: "m_smoker",
    flavorProfileId: "f_tangy",
    recipeType: "brine" as const,
    ingredients: ["4 cups apple juice", "1/2 cup apple cider vinegar", "1/4 cup salt", "1/4 cup brown sugar", "4 whole cloves"],
    instructions: ["Mix all ingredients until salt and sugar dissolve.", "Submerge ribs for 4-6 hours.", "Remove, pat dry, and apply a light rub before smoking."],
    prepTime: "6 hours",
    cookTime: "5 hours",
    restingTime: "15 min",
    targetTempF: 195,
    woodPairings: ["Cherry", "Apple"],
    sauceRecommendations: ["Apple Butter BBQ Sauce"],
    sideRecommendations: ["Onion Rings", "Coleslaw"],
    cookingTips: ["Brining ribs makes them exceptionally juicy and slightly cured in flavor."]
  },
  // --- POULTRY ---
  // Chicken (Current: 1 Marinade [Spicy])
  {
    id: crypto.randomUUID(),
    title: "Classic Savory Herb Chicken Rub",
    proteinId: "p_chicken",
    cookingMethodId: "m_gas_grill",
    flavorProfileId: "f_savory_herb",
    recipeType: "dry_rub" as const,
    ingredients: ["2 tbsp kosher salt", "1 tbsp dried thyme", "1 tbsp dried sage", "1 tbsp dried rosemary", "1 tbsp garlic powder", "1 tbsp onion powder", "1 tsp white pepper"],
    instructions: ["Mix all spices in a small bowl.", "Spatchcock or piece the chicken for even cooking.", "Apply rub under the skin and on the surface.", "Grill over medium heat until 165°F internal."],
    prepTime: "15 min",
    cookTime: "45 min",
    restingTime: "10 min",
    targetTempF: 165,
    woodPairings: ["Apple", "Cherry"],
    sauceRecommendations: ["White Wine Mushroom Sauce"],
    sideRecommendations: ["Roasted Potatoes", "Green Salad"],
    cookingTips: ["Applying rub under the skin seasons the meat directly and prevents the skin from shielding it."]
  },
  {
    id: crypto.randomUUID(),
    title: "Sweet & Smoky Chipotle Chicken Rub",
    proteinId: "p_chicken",
    cookingMethodId: "m_pellet_grill",
    flavorProfileId: "f_sweet_smoky",
    recipeType: "dry_rub" as const,
    ingredients: ["1/4 cup paprika", "2 tbsp brown sugar", "1 tbsp chipotle powder", "1 tbsp garlic powder", "1 tbsp onion powder", "1 tsp celery salt", "1 tsp black pepper"],
    instructions: ["Combine all ingredients.", "Apply liberally to chicken thighs or legs.", "Smoke at 275°F for 1.5 - 2 hours until skin is bite-through and meat is 175°F (for dark meat).", "Rest for 10 minutes."],
    prepTime: "10 min",
    cookTime: "2 hours",
    restingTime: "10 min",
    targetTempF: 175,
    woodPairings: ["Hickory", "Maple"],
    sauceRecommendations: ["Honey Chipotle BBQ Sauce"],
    sideRecommendations: ["Mac and Cheese", "Coleslaw"],
    cookingTips: ["Dark meat (thighs/legs) benefits from a slightly higher final temp for better texture."]
  },
  {
    id: crypto.randomUUID(),
    title: "Tangy Lemon Herb Chicken Marinade",
    proteinId: "p_chicken",
    cookingMethodId: "m_charcoal_grill",
    flavorProfileId: "f_tangy",
    recipeType: "marinade" as const,
    ingredients: ["1/2 cup Greek yogurt", "1/4 cup lemon juice", "2 tbsp olive oil", "4 cloves garlic, minced", "1 tbsp dried oregano", "1 tsp salt", "1/2 tsp black pepper"],
    instructions: ["Whisk all ingredients together.", "Coat chicken pieces thoroughly and marinate for 2-4 hours.", "Grill over medium charcoal heat, turning occasionally to prevent scorching.", "Cook until 165°F."],
    prepTime: "2 hours",
    cookTime: "30 min",
    restingTime: "5 min",
    targetTempF: 165,
    woodPairings: ["Fruitwood"],
    sauceRecommendations: ["Tzatziki"],
    sideRecommendations: ["Grilled Veggie Kabobs", "Rice Pilaf"],
    cookingTips: ["The lactic acid in yogurt tenderizes chicken more gently than vinegar."]
  },
  {
    id: crypto.randomUUID(),
    title: "Savory Buttermilk Chicken Brine",
    proteinId: "p_chicken",
    cookingMethodId: "m_oven",
    flavorProfileId: "f_savory_herb",
    recipeType: "brine" as const,
    ingredients: ["2 cups buttermilk", "1/4 cup hot sauce", "2 tbsp salt", "1 tbsp garlic powder", "1 tsp black peppercorns"],
    instructions: ["Combine all ingredients in a large bowl or bag.", "Submerge chicken pieces for 4-8 hours.", "Remove from brine, drain excess, and bake at 400°F until golden and cooked through.", "Great for 'oven-fried' style chicken."],
    prepTime: "4 hours",
    cookTime: "40 min",
    restingTime: "5 min",
    targetTempF: 165,
    woodPairings: [],
    sauceRecommendations: ["Ranch dressing", "Honey Mustard"],
    sideRecommendations: ["Mashed Potatoes", "Corn"],
    cookingTips: ["Buttermilk brine is the secret to incredibly juicy and tender chicken."]
  },

  // Turkey (Current: 1 Rub [Savory Herb])
  {
    id: crypto.randomUUID(),
    title: "Tangy Lemon Pepper Turkey Rub",
    proteinId: "p_turkey",
    cookingMethodId: "m_pellet_grill",
    flavorProfileId: "f_tangy",
    recipeType: "dry_rub" as const,
    ingredients: ["2 tbsp lemon pepper seasoning", "1 tbsp garlic powder", "1 tbsp onion powder", "1 tbsp dried parsley", "1 tsp salt", "1 tsp black pepper"],
    instructions: ["Pat turkey breast or whole bird dry.", "Apply rub liberally over the skin and inside the cavity.", "Smoke at 325°F until the thickest part reaches 165°F.", "Higher temps help crisp the turkey skin."],
    prepTime: "15 min",
    cookTime: "3 hours",
    restingTime: "30 min",
    targetTempF: 165,
    woodPairings: ["Pecan", "Cherry"],
    sauceRecommendations: ["Cranberry Sauce", "Gravy"],
    sideRecommendations: ["Stuffing", "Roasted Sprouts"],
    cookingTips: ["Turkey skin can get rubbery at low smoker temps; 325°F is the sweet spot."]
  },
  {
    id: crypto.randomUUID(),
    title: "Savory White Wine & Garlic Turkey Marinade",
    proteinId: "p_turkey",
    cookingMethodId: "m_oven",
    flavorProfileId: "f_savory_herb",
    recipeType: "marinade" as const,
    ingredients: ["1/2 cup melted butter", "1/2 cup dry white wine", "4 cloves garlic, minced", "1 tbsp fresh sage, chopped", "1 tbsp fresh thyme, chopped", "1 tsp salt"],
    instructions: ["Whisk all ingredients.", "Place turkey breast in a roasting pan and pour marinade over, ensuring some goes under the skin.", "Let sit for 1 hour.", "Roast at 350°F, basting every 30 minutes with the pan juices."],
    prepTime: "1 hour",
    cookTime: "2 hours",
    restingTime: "20 min",
    targetTempF: 165,
    woodPairings: [],
    sauceRecommendations: ["Pan drippings gravy"],
    sideRecommendations: ["Dinner rolls", "Glazed Carrots"],
    cookingTips: ["Butter and wine create a rich, savory self-basting environment."]
  },
  {
    id: crypto.randomUUID(),
    title: "Sweet & Smoky Maple Cider Turkey Marinade",
    proteinId: "p_turkey",
    cookingMethodId: "m_smoker",
    flavorProfileId: "f_sweet_smoky",
    recipeType: "marinade" as const,
    ingredients: ["1 cup apple cider", "1/4 cup maple syrup", "2 tbsp olive oil", "1 tbsp smoked paprika", "1 tsp salt", "1 tsp black pepper"],
    instructions: ["Combine all ingredients.", "Marinate turkey breast for 4-6 hours.", "Smoke at 275°F until 165°F internal.", "The maple syrup creates a beautiful dark glaze."],
    prepTime: "4 hours",
    cookTime: "3 hours",
    restingTime: "20 min",
    targetTempF: 165,
    woodPairings: ["Maple", "Apple"],
    sauceRecommendations: ["Maple Bourbon Glaze"],
    sideRecommendations: ["Sweet Potato Casserole", "Pecans"],
    cookingTips: ["Maple syrup can burn if the temp is too high; keep the smoker under 300°F."]
  },
  {
    id: crypto.randomUUID(),
    title: "Tangy Apple Cider Vinegar Turkey Brine",
    proteinId: "p_turkey",
    cookingMethodId: "m_pellet_grill",
    flavorProfileId: "f_tangy",
    recipeType: "brine" as const,
    ingredients: ["2 quarts water", "1/2 cup salt", "1/2 cup sugar", "1/2 cup apple cider vinegar", "1 tbsp black peppercorns", "3 bay leaves"],
    instructions: ["Dissolve salt and sugar in 1 quart of warm water.", "Add vinegar, peppercorns, bay leaves, and remaining cold water.", "Brine turkey for 12-24 hours.", "Rinse and pat extremely dry before smoking to ensure crispy skin."],
    prepTime: "24 hours",
    cookTime: "3.5 hours",
    restingTime: "30 min",
    targetTempF: 165,
    woodPairings: ["Cherry", "Oak"],
    sauceRecommendations: ["Mustard-based BBQ Sauce"],
    sideRecommendations: ["Cornbread dressing", "Green Bean Casserole"],
    cookingTips: ["A long brine is essential for whole turkeys to prevent breast meat from drying out."]
  },
  // --- SEAFOOD ---
  // Salmon (Current: 1 Marinade [Tangy])
  {
    id: crypto.randomUUID(),
    title: "Lemon & Dill Savory Salmon Rub",
    proteinId: "p_salmon",
    cookingMethodId: "m_gas_grill",
    flavorProfileId: "f_savory_herb",
    recipeType: "dry_rub" as const,
    ingredients: ["1 tbsp kosher salt", "1 tbsp dried dill", "1 tbsp dried parsley", "1 tsp garlic powder", "1 tsp onion powder", "1/2 tsp lemon zest", "1/4 tsp white pepper"],
    instructions: ["Mix all rub ingredients.", "Brush salmon fillets with a tiny bit of olive oil.", "Press the rub onto the flesh side of the salmon.", "Grill skin-side down first at 375°F until flesh is opaque and flakes easily."],
    prepTime: "10 min",
    cookTime: "12 min",
    restingTime: "2 min",
    targetTempF: 145,
    woodPairings: ["Alder", "Cedar"],
    sauceRecommendations: ["Dill Cream Sauce"],
    sideRecommendations: ["Asparagus", "Rice Pilaf"],
    cookingTips: ["Skin-on salmon is easier to handle on the grill and stays moister."]
  },
  {
    id: crypto.randomUUID(),
    title: "Sweet & Spicy Chipotle Salmon Rub",
    proteinId: "p_salmon",
    cookingMethodId: "m_pellet_grill",
    flavorProfileId: "f_spicy",
    recipeType: "dry_rub" as const,
    ingredients: ["2 tbsp brown sugar", "1 tbsp chipotle powder", "1 tsp cumin", "1 tsp salt", "1/2 tsp black pepper"],
    instructions: ["Combine ingredients.", "Rub liberally onto salmon fillets.", "Smoke at 225°F for 45-60 minutes until internal temp reaches 140°F (it will carry over to 145°F).", "The sugar will caramelize into a nice glaze."],
    prepTime: "5 min",
    cookTime: "1 hour",
    restingTime: "5 min",
    targetTempF: 145,
    woodPairings: ["Cherry", "Apple"],
    sauceRecommendations: ["Chipotle Mayo"],
    sideRecommendations: ["Mango Salsa", "Black Beans"],
    cookingTips: ["Low and slow smoking keeps salmon incredibly buttery."]
  },
  {
    id: crypto.randomUUID(),
    title: "Spicy Honey Ginger Salmon Marinade",
    proteinId: "p_salmon",
    cookingMethodId: "m_charcoal_grill",
    flavorProfileId: "f_spicy",
    recipeType: "marinade" as const,
    ingredients: ["2 tbsp honey", "1 tbsp sriracha", "1 tbsp soy sauce", "1 tbsp lime juice", "1 tsp grated ginger", "1 clove garlic, minced"],
    instructions: ["Whisk all ingredients.", "Marinate salmon for 30-60 minutes.", "Grill over medium charcoal heat, basting once with fresh (un-used) marinade.", "Cook until 145°F."],
    prepTime: "1 hour",
    cookTime: "10 min",
    restingTime: "2 min",
    targetTempF: 145,
    woodPairings: ["Oak"],
    sauceRecommendations: ["Extra Sriracha Honey Glaze"],
    sideRecommendations: ["Baby Bok Choy", "Soba Noodles"],
    cookingTips: ["Honey burns easily, so keep a close eye on the charcoal grill."]
  },
  {
    id: crypto.randomUUID(),
    title: "Savory Maple Dill Salmon Brine",
    proteinId: "p_salmon",
    cookingMethodId: "m_pellet_grill",
    flavorProfileId: "f_savory_herb",
    recipeType: "brine" as const,
    ingredients: ["4 cups water", "1/4 cup kosher salt", "1/4 cup maple syrup", "2 tbsp fresh dill, chopped", "1 tsp black peppercorns"],
    instructions: ["Mix water, salt, and syrup until dissolved.", "Add dill and peppercorns.", "Brine salmon for 2-3 hours.", "Rinse, pat dry, and let sit in the fridge for 1 hour to form a 'pellicle' (tacky surface) before smoking."],
    prepTime: "4 hours",
    cookTime: "1 hour",
    restingTime: "5 min",
    targetTempF: 145,
    woodPairings: ["Alder", "Maple"],
    sauceRecommendations: ["Maple Glaze"],
    sideRecommendations: ["Roasted Root Veggies", "Quinoa"],
    cookingTips: ["The pellicle helps the smoke stick to the fish better."]
  },

  // Shrimp (Current: 1 Rub [Spicy])
  {
    id: crypto.randomUUID(),
    title: "Savory Herb Old Bay Style Shrimp Rub",
    proteinId: "p_shrimp",
    cookingMethodId: "m_charcoal_grill",
    flavorProfileId: "f_savory_herb",
    recipeType: "dry_rub" as const,
    ingredients: ["1 tbsp celery salt", "1 tsp smoked paprika", "1 tsp black pepper", "1/2 tsp cayenne", "1/2 tsp dry mustard", "1/4 tsp ground cloves"],
    instructions: ["Mix all spices.", "Toss peeled and deveined shrimp with a little oil and the rub.", "Grill on skewers over high charcoal heat for 2 minutes per side.", "Serve with lemon."],
    prepTime: "15 min",
    cookTime: "4 min",
    restingTime: "0 min",
    targetTempF: 145,
    woodPairings: [],
    sauceRecommendations: ["Cocktail Sauce", "Clarified Butter"],
    sideRecommendations: ["Corn on the Cob", "Potato Salad"],
    cookingTips: ["Shrimp cook very fast; they are done when they form a 'C' shape."]
  },
  {
    id: crypto.randomUUID(),
    title: "Savory Lemon Garlic Shrimp Marinade",
    proteinId: "p_shrimp",
    cookingMethodId: "m_gas_grill",
    flavorProfileId: "f_savory_herb",
    recipeType: "marinade" as const,
    ingredients: ["1/4 cup olive oil", "2 tbsp lemon juice", "3 cloves garlic, minced", "1 tsp dried basil", "1 tsp dried oregano", "1/2 tsp salt"],
    instructions: ["Whisk ingredients.", "Marinate shrimp for 20-30 minutes.", "Grill over medium-high heat on skewers or in a grill basket.", "Cook until pink and opaque."],
    prepTime: "30 min",
    cookTime: "5 min",
    restingTime: "0 min",
    targetTempF: 145,
    woodPairings: [],
    sauceRecommendations: ["Garlic Butter"],
    sideRecommendations: ["Pasta", "Grilled Bread"],
    cookingTips: ["Don't marinate shrimp in citrus for more than 30 mins or they will start to 'cook' (ceviche style)."]
  },
  {
    id: crypto.randomUUID(),
    title: "Spicy Tequila Lime Shrimp Marinade",
    proteinId: "p_shrimp",
    cookingMethodId: "m_charcoal_grill",
    flavorProfileId: "f_spicy",
    recipeType: "marinade" as const,
    ingredients: ["2 tbsp tequila", "2 tbsp lime juice", "1 tbsp olive oil", "1 jalapeño, minced", "2 tbsp fresh cilantro, chopped", "1/2 tsp salt"],
    instructions: ["Combine all ingredients.", "Marinate shrimp for 30 minutes.", "Grill over hot charcoal for a nice char.", "Serve in tacos."],
    prepTime: "35 min",
    cookTime: "4 min",
    restingTime: "2 min",
    targetTempF: 145,
    woodPairings: ["Mesquite"],
    sauceRecommendations: ["Avocado Crema"],
    sideRecommendations: ["Street Corn", "Cabbage Slaw"],
    cookingTips: ["The alcohol in tequila helps carry the flavors deep into the shrimp."]
  },
  {
    id: crypto.randomUUID(),
    title: "Spicy Red Pepper Shrimp Brine",
    proteinId: "p_shrimp",
    cookingMethodId: "m_charcoal_grill",
    flavorProfileId: "f_spicy",
    recipeType: "brine" as const,
    ingredients: ["4 cups water", "1/4 cup salt", "1/4 cup sugar", "1 tbsp red pepper flakes", "2 cloves garlic, crushed", "1/2 lemon, sliced"],
    instructions: ["Dissolve salt and sugar in water.", "Add pepper flakes, garlic, and lemon.", "Brine shrimp for only 15-20 minutes.", "Rinse well and pat dry before grilling."],
    prepTime: "20 min",
    cookTime: "4 min",
    restingTime: "0 min",
    targetTempF: 145,
    woodPairings: [],
    sauceRecommendations: ["Spicy Remoulade"],
    sideRecommendations: ["Cajun Dirty Rice", "Fried Green Tomatoes"],
    cookingTips: ["Brining shrimp makes them incredibly 'snappy' and plump."]
  },
  // --- VEGETABLES ---
  // Mixed Veggies (Current: 1 Marinade [Savory Herb])
  {
    id: crypto.randomUUID(),
    title: "Umami Savory Herb Veggie Rub",
    proteinId: "p_veg_mixed",
    cookingMethodId: "m_oven",
    flavorProfileId: "f_savory_herb",
    recipeType: "dry_rub" as const,
    ingredients: ["2 tbsp nutritional yeast", "1 tbsp garlic powder", "1 tbsp onion powder", "1 tsp dried thyme", "1 tsp dried rosemary", "1 tsp salt", "1/2 tsp black pepper"],
    instructions: ["Mix all dry ingredients.", "Toss chopped vegetables with a little oil.", "Sprinkle the rub over the veggies and toss to coat.", "Roast at 400°F until tender and slightly caramelized."],
    prepTime: "10 min",
    cookTime: "25 min",
    restingTime: "0 min",
    targetTempF: 160,
    woodPairings: [],
    sauceRecommendations: ["Lemon Tahini Dressing"],
    sideRecommendations: ["Quinoa", "Grilled Halloumi"],
    cookingTips: ["Nutritional yeast adds a savory, cheesy flavor without the dairy."]
  },
  {
    id: crypto.randomUUID(),
    title: "Sweet & Smoky Mesquite Veggie Rub",
    proteinId: "p_veg_mixed",
    cookingMethodId: "m_charcoal_grill",
    flavorProfileId: "f_sweet_smoky",
    recipeType: "dry_rub" as const,
    ingredients: ["2 tbsp brown sugar", "1 tbsp smoked paprika", "1 tsp smoked salt", "1 tsp chili powder", "1/2 tsp cumin", "1/2 tsp garlic powder"],
    instructions: ["Combine all spices.", "Toss veggies (like corn or bell peppers) with oil and the rub.", "Grill over direct charcoal heat for a nice char and smoky finish."],
    prepTime: "10 min",
    cookTime: "10 min",
    restingTime: "0 min",
    targetTempF: 160,
    woodPairings: ["Mesquite"],
    sauceRecommendations: ["Chipotle Ranch"],
    sideRecommendations: ["Black Bean Salad"],
    cookingTips: ["The sugar in the rub helps get those beautiful grill marks on vegetables."]
  },
  {
    id: crypto.randomUUID(),
    title: "Sweet & Smoky Balsamic Veggie Marinade",
    proteinId: "p_veg_mixed",
    cookingMethodId: "m_gas_grill",
    flavorProfileId: "f_sweet_smoky",
    recipeType: "marinade" as const,
    ingredients: ["1/4 cup balsamic vinegar", "2 tbsp honey", "1/4 cup olive oil", "1/2 tsp liquid smoke", "2 cloves garlic, minced", "Salt and pepper"],
    instructions: ["Whisk ingredients.", "Marinate sturdy veggies (mushrooms, onions, peppers) for 1 hour.", "Grill over medium heat until tender, basting with remaining marinade."],
    prepTime: "1 hour",
    cookTime: "12 min",
    restingTime: "0 min",
    targetTempF: 160,
    woodPairings: [],
    sauceRecommendations: ["Balsamic Glaze"],
    sideRecommendations: ["Polenta", "Crusty Bread"],
    cookingTips: ["Liquid smoke provides that outdoor flavor even on a gas grill."]
  },
  {
    id: crypto.randomUUID(),
    title: "Savory Garden Herb Veggie Brine",
    proteinId: "p_veg_mixed",
    cookingMethodId: "m_oven",
    flavorProfileId: "f_savory_herb",
    recipeType: "brine" as const,
    ingredients: ["4 cups water", "2 tbsp salt", "1 tbsp sugar", "2 cloves garlic", "1 bay leaf", "3 sprigs fresh thyme"],
    instructions: ["Dissolve salt and sugar in water.", "Add garlic, bay leaf, and thyme.", "Brine dense veggies (like cauliflower or potatoes) for 1-2 hours.", "Drain, pat dry, and roast until tender."],
    prepTime: "2 hours",
    cookTime: "30 min",
    restingTime: "0 min",
    targetTempF: 160,
    woodPairings: [],
    sauceRecommendations: ["Herb Butter"],
    sideRecommendations: ["Steak", "Roasted Chicken"],
    cookingTips: ["Brining dense vegetables ensures they are seasoned all the way through."]
  },
];
