
export const newTypeTemplates = [
  // --- STEAK (Needs Compound Butter & Sauce) ---
  {
    id: crypto.randomUUID(),
    title: "Garlic & Herb Compound Butter",
    proteinId: "p_steak",
    cookingMethodId: "m_charcoal_grill",
    flavorProfileId: "f_savory_herb",
    recipeType: "compound_butter" as const,
    ingredients: ["1/2 cup unsalted butter, softened", "2 cloves garlic, minced", "1 tbsp fresh parsley, chopped", "1 tsp fresh thyme, chopped", "1/2 tsp kosher salt", "1/4 tsp black pepper"],
    instructions: ["In a small bowl, combine all ingredients.", "Mix until well combined.", "Place on plastic wrap and roll into a log.", "Refrigerate for at least 1 hour before slicing.", "Top hot steak with a slice of butter just before serving."],
    prepTime: "10 min",
    cookTime: "0 min",
    restingTime: "1 hour",
    targetTempF: 0,
    woodPairings: ["Oak"],
    sauceRecommendations: ["None"],
    sideRecommendations: ["Mashed Potatoes"],
    cookingTips: ["Make this a day ahead to let the flavors fully meld."]
  },
  {
    id: crypto.randomUUID(),
    title: "Blue Cheese & Peppercorn Compound Butter",
    proteinId: "p_steak",
    cookingMethodId: "m_gas_grill",
    flavorProfileId: "f_texas_classic",
    recipeType: "compound_butter" as const,
    ingredients: ["1/2 cup unsalted butter, softened", "1/4 cup crumbled blue cheese", "1 tsp cracked black pepper", "1/2 tsp salt"],
    instructions: ["Mash butter and blue cheese together with a fork.", "Stir in pepper and salt.", "Form into a log and chill.", "Serve a thick slice over a hot seared steak."],
    prepTime: "10 min",
    cookTime: "0 min",
    restingTime: "1 hour",
    targetTempF: 0,
    woodPairings: ["Hickory"],
    sauceRecommendations: ["None"],
    sideRecommendations: ["Steak Fries"],
    cookingTips: ["The sharp blue cheese cuts through the richness of the beef."]
  },
  {
    id: crypto.randomUUID(),
    title: "Classic Chimichurri Sauce",
    proteinId: "p_steak",
    cookingMethodId: "m_charcoal_grill",
    flavorProfileId: "f_savory_herb",
    recipeType: "sauce" as const,
    ingredients: ["1 cup fresh parsley, packed", "4 cloves garlic", "2 tbsp fresh oregano (or 1 tsp dried)", "1/2 cup olive oil", "2 tbsp red wine vinegar", "1 tsp sea salt", "1/4 tsp red pepper flakes"],
    instructions: ["Finely chop parsley, garlic, and oregano.", "Mix in a bowl with oil, vinegar, salt, and pepper flakes.", "Let sit for at least 20 minutes at room temperature before serving.", "Spoon over grilled steak."],
    prepTime: "15 min",
    cookTime: "0 min",
    restingTime: "20 min",
    targetTempF: 0,
    woodPairings: ["Oak"],
    sauceRecommendations: ["None"],
    sideRecommendations: ["Grilled Vegetables"],
    cookingTips: ["Do not use a food processor; hand-chopping gives the best texture."]
  },
  {
    id: crypto.randomUUID(),
    title: "Smoky Bourbon Peppercorn Sauce",
    proteinId: "p_steak",
    cookingMethodId: "m_gas_grill",
    flavorProfileId: "f_sweet_smoky",
    recipeType: "sauce" as const,
    ingredients: ["1/4 cup bourbon", "1/2 cup beef broth", "1/4 cup heavy cream", "1 tbsp cracked black pepper", "1 tbsp shallot, minced", "1 tbsp butter"],
    instructions: ["Sauté shallots in butter until soft.", "Add bourbon and carefully flambé or simmer until reduced by half.", "Add beef broth and pepper; reduce by half again.", "Stir in cream and simmer until thickened.", "Serve warm over steak."],
    prepTime: "5 min",
    cookTime: "15 min",
    restingTime: "0 min",
    targetTempF: 0,
    woodPairings: ["Pecan"],
    sauceRecommendations: ["None"],
    sideRecommendations: ["Roasted Fingerling Potatoes"],
    cookingTips: ["The bourbon adds a sweet, oaky depth that pairs well with smoked meats."]
  },

  // --- CHICKEN (Needs Glazes) ---
  {
    id: crypto.randomUUID(),
    title: "Honey & Smoked Paprika Glaze",
    proteinId: "p_chicken",
    cookingMethodId: "m_pellet_grill",
    flavorProfileId: "f_sweet_smoky",
    recipeType: "glaze" as const,
    ingredients: ["1/2 cup honey", "2 tbsp apple cider vinegar", "1 tbsp smoked paprika", "1 tsp garlic powder", "1/2 tsp cayenne pepper"],
    instructions: ["Whisk all ingredients in a small saucepan.", "Simmer over low heat for 5 minutes until slightly thickened.", "Brush onto chicken during the last 10-15 minutes of cooking.", "Apply in thin layers for a tacky finish."],
    prepTime: "5 min",
    cookTime: "5 min",
    restingTime: "0 min",
    targetTempF: 0,
    woodPairings: ["Cherry", "Apple"],
    sauceRecommendations: ["None"],
    sideRecommendations: ["Cornbread"],
    cookingTips: ["Applying too early will cause the honey to burn; wait until the end."]
  },
  {
    id: crypto.randomUUID(),
    title: "Lemon & Thyme Butter Glaze",
    proteinId: "p_chicken",
    cookingMethodId: "m_gas_grill",
    flavorProfileId: "f_savory_herb",
    recipeType: "glaze" as const,
    ingredients: ["1/4 cup melted butter", "2 tbsp fresh lemon juice", "1 tsp lemon zest", "1 tbsp fresh thyme, chopped", "1/2 tsp salt"],
    instructions: ["Combine all ingredients in a bowl.", "Baste onto chicken every 10 minutes during grilling.", "Finish with an extra coat just before removing from heat."],
    prepTime: "5 min",
    cookTime: "0 min",
    restingTime: "0 min",
    targetTempF: 0,
    woodPairings: ["Pecan"],
    sauceRecommendations: ["None"],
    sideRecommendations: ["Green Beans"],
    cookingTips: ["The butter helps the skin crisp up while the lemon keeps it bright."]
  },
  {
    id: crypto.randomUUID(),
    title: "Tangy Carolina Gold Glaze",
    proteinId: "p_chicken",
    cookingMethodId: "m_smoker",
    flavorProfileId: "f_tangy",
    recipeType: "glaze" as const,
    ingredients: ["1/2 cup yellow mustard", "1/4 cup honey", "1/4 cup apple cider vinegar", "1 tbsp brown sugar", "1 tsp Worcestershire sauce"],
    instructions: ["Mix all ingredients thoroughly.", "Brush onto chicken quarters during the final 20 minutes of smoking.", "Repeat every 10 minutes until a deep gold color is achieved."],
    prepTime: "5 min",
    cookTime: "0 min",
    restingTime: "0 min",
    targetTempF: 0,
    woodPairings: ["Hickory"],
    sauceRecommendations: ["None"],
    sideRecommendations: ["Coleslaw"],
    cookingTips: ["This glaze is a mustard-lover's dream and works perfectly with poultry fat."]
  },

  // --- SEAFOOD (Needs Glazes) ---
  {
    id: crypto.randomUUID(),
    title: "Garlic Butter & Dill Seafood Glaze",
    proteinId: "p_salmon",
    cookingMethodId: "m_gas_grill",
    flavorProfileId: "f_savory_herb",
    recipeType: "glaze" as const,
    ingredients: ["4 tbsp unsalted butter", "2 cloves garlic, minced", "1 tbsp fresh dill, chopped", "1 tsp lemon juice"],
    instructions: ["Melt butter in a small pan.", "Add garlic and sauté for 1 minute until fragrant.", "Stir in dill and lemon juice.", "Brush liberally over salmon or shrimp during the last 3-4 minutes of grilling."],
    prepTime: "5 min",
    cookTime: "2 min",
    restingTime: "0 min",
    targetTempF: 0,
    woodPairings: ["Alder"],
    sauceRecommendations: ["None"],
    sideRecommendations: ["Rice Pilaf"],
    cookingTips: ["Dill and salmon are the ultimate pairing; use fresh dill if possible."]
  },
  {
    id: crypto.randomUUID(),
    title: "Spicy Sriracha Lime Glaze",
    proteinId: "p_shrimp",
    cookingMethodId: "m_charcoal_grill",
    flavorProfileId: "f_spicy",
    recipeType: "glaze" as const,
    ingredients: ["2 tbsp sriracha", "2 tbsp honey", "1 tbsp lime juice", "1 tsp soy sauce"],
    instructions: ["Whisk ingredients together.", "Baste onto shrimp skewers for the last 2 minutes of grilling.", "Turn skewers to ensure even caramelization."],
    prepTime: "5 min",
    cookTime: "0 min",
    restingTime: "0 min",
    targetTempF: 0,
    woodPairings: ["Fruitwood"],
    sauceRecommendations: ["Extra glaze for dipping"],
    sideRecommendations: ["Mango Slaw"],
    cookingTips: ["The heat from the sriracha is balanced by the honey's sweetness."]
  },

  // --- VEGGIES (Needs Glazes) ---
  {
    id: crypto.randomUUID(),
    title: "Maple Balsamic Veggie Glaze",
    proteinId: "p_veg_mixed",
    cookingMethodId: "m_oven",
    flavorProfileId: "f_sweet_smoky",
    recipeType: "glaze" as const,
    ingredients: ["2 tbsp balsamic glaze (reduced)", "1 tbsp maple syrup", "1 tbsp olive oil", "1/2 tsp smoked salt"],
    instructions: ["Whisk ingredients until smooth.", "Toss with roasted vegetables halfway through cooking.", "Apply a final coat just before serving."],
    prepTime: "5 min",
    cookTime: "0 min",
    restingTime: "0 min",
    targetTempF: 0,
    woodPairings: ["None"],
    sauceRecommendations: ["None"],
    sideRecommendations: ["Goat Cheese"],
    cookingTips: ["The maple syrup helps the balsamic stick to the veggies and caramelize."]
  },
  {
    id: crypto.randomUUID(),
    title: "Roasted Garlic & Herb Oil Glaze",
    proteinId: "p_veg_mixed",
    cookingMethodId: "m_gas_grill",
    flavorProfileId: "f_savory_herb",
    recipeType: "glaze" as const,
    ingredients: ["1/4 cup olive oil", "4 cloves roasted garlic, mashed", "1 tsp dried rosemary", "1 tsp dried thyme"],
    instructions: ["Whisk mashed garlic into oil.", "Add herbs and let sit for 10 minutes.", "Brush over vegetables throughout the grilling process."],
    prepTime: "15 min",
    cookTime: "0 min",
    restingTime: "10 min",
    targetTempF: 0,
    woodPairings: ["Oak"],
    sauceRecommendations: ["None"],
    sideRecommendations: ["Crusty Bread"],
    cookingTips: ["Roasted garlic has a milder, sweeter flavor than raw garlic."]
  },

  // --- ADDITIONAL SAUCES (Pork/Beef) ---
  {
    id: crypto.randomUUID(),
    title: "Spicy Chipotle BBQ Sauce",
    proteinId: "p_pork_butt",
    cookingMethodId: "m_smoker",
    flavorProfileId: "f_spicy",
    recipeType: "sauce" as const,
    ingredients: ["1 cup ketchup", "2 tbsp adobo sauce (from chipotle can)", "1 chipotle pepper, minced", "2 tbsp brown sugar", "1 tbsp cider vinegar"],
    instructions: ["Combine all ingredients in a saucepan.", "Simmer for 10 minutes until thick and glossy.", "Serve on the side with pulled pork."],
    prepTime: "5 min",
    cookTime: "10 min",
    restingTime: "0 min",
    targetTempF: 0,
    woodPairings: ["Hickory"],
    sauceRecommendations: ["None"],
    sideRecommendations: ["Corn"],
    cookingTips: ["Add more adobo sauce if you want more smoke and heat."]
  },
  {
    id: crypto.randomUUID(),
    title: "Sweet & Smoky Bourbon BBQ Sauce",
    proteinId: "p_ribs",
    cookingMethodId: "m_smoker",
    flavorProfileId: "f_sweet_smoky",
    recipeType: "sauce" as const,
    ingredients: ["1 cup ketchup", "1/4 cup bourbon", "1/4 cup molasses", "2 tbsp Worcestershire sauce", "1 tsp liquid smoke"],
    instructions: ["Simmer ingredients in a pan for 15 minutes.", "Let cool before serving.", "Ideal for slathering on ribs."],
    prepTime: "5 min",
    cookTime: "15 min",
    restingTime: "0 min",
    targetTempF: 0,
    woodPairings: ["Cherry"],
    sauceRecommendations: ["None"],
    sideRecommendations: ["Baked Beans"],
    cookingTips: ["The molasses provides a thick, dark, and rich consistency."]
  }
];
